
User Guide
---------------
This part of the guide focuses on setting up your environment for TIBS and Generic Pos, including Pub, Hub and Pos. A quickstart is then presented to give an overview of TIBS and Generic POS. Finally, details of each components are presented. 

.. toctree::
    :maxdepth: 2

    guide/install
    guide/quickstart
    guide/tibs
    guide/pub
    guide/hub
    guide/pos
    
    

Design Note
-----------
.. toctree::
    :maxdepth: 2

    design/scenarios
    design/datalayout


API Reference
-------------
This part of the documentation dedicates to prople who are looking for information on a specific function, class or method.

.. toctree::
    :maxdepth: 3

    api/pub
    api/hub
    api/pos

Additional Note
---------------
This part of note declares the license of TIBS. 

.. toctree::
    :maxdepth: 2

    license
